### PR TITLE
Dev mode styling

### PR DESCRIPTION
**Pull request by 1aurend**
@jsbean do you have a minute to check this out and make sure we've got the colors right and everything merges properly? @philsometimes finished some additional layout updates, and I'd love to get this up in the next heroku push, which I can do tonight as soon as I get the okay from you and @davidforrest.

### CODE REVIEW

**Comment by philsometimes** [comment]
@jsbean : 
*this still has the old grey and green colors
**the new layout stuff was done to mockups, check them out at localhost:3000/start, /quiz, /stats, /chart, and /table. I'll have everything in the real files in an hour

**Comment by philsometimes** [comment]
okay I'm happy—fixed everything I raised, good to merge from my end

**Comment by jsbean** [comment]
@1aurend, @philsometimes: Ah, just getting to this. Pulling it down and trying it out!

**Comment by jsbean** [comment]
LGTM! 🚀

**Pull request merged**
