### PR TITLE
Prepare CI testing infrastructure

### PR DESCRIPTION
**Pull request by jsbean**
This PR attempts to use ~~Github Actions~~ [Travis CI](https://travis-ci.org) to run CI (Continuous Integration) testing.

There are many unknowns for me at the moment, so this PR will undoubtedly be a document of me incoherently bumping into things in the dark.

Hooking into a CI server allows us to test our code on a clean server every time we want to make a commit. A nice UI will show up right in the PR showing us that it is passing or not. (We can even choose to block commits which don't pass the tests!) We can also do nice things like add a badge to the README which shows the current testing status.

### CODE REVIEW

**Comment by jsbean** [comment]
@1aurend, would you be interested in trying to add this repository to [Travis CI](https://travis-ci.org)?

You should be able to sign into Travis CI with your Github account. Then you press a `+` button somewhere to Add a Repository. It _should_ be straightforward. You may need to "refresh" the repositories in the view of Travis CI.

**Comment by 1aurend** [comment]
@jsbean I activated it, and it's building something, but I don't know what it means... 🙃

**Comment by 1aurend** [comment]
It's giving me a bunch of warnings re: using an old version of node. We need to reconcile updates to dependencies at some point. I think I've run some updates over in `ui-refactor`. But also we should think about whether we want to eject from `create-react-app` at some point to be able to do a more custom config.

**Comment by jsbean** [comment]
Wahoo, thanks for setting up Travis. Now we've got the details in-line here in the PR.

It'll be awkward for the next while, but I'll get the config sorted out so everyone is happy in Travis land.

**Comment by jsbean** [comment]
Oh whoops. That was easy.

**Pull request merged**
