### PR TITLE
Disable snapshot tests momentarily

### PR DESCRIPTION
**Pull request by jsbean**
This PR disables a couple of snapshot tests which are failing on my machine and on Travis.

@1aurend, perhaps this is interesting to you. More than anything, help me remember to re-enable these prior to merging into `master`.

### CODE REVIEW

**Comment by jsbean** [comment]
@1aurend, do you get this warning / error on your machine?

```Bash
console.error node_modules/react-dom/cjs/react-dom.development.js:530
351      Warning: React does not recognize the `randomElement` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `randomelement` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
352          in h2 (at QuizQuestion.js:45)
353          in div (created by Row)
354          in Row (created by Styled(Row))
355          in Styled(Row) (at QuizQuestion.js:44)
356          in div (created by Col)
357          in Col (created by Styled(Col))
358          in Styled(Col) (at QuizQuestion.js:43)
359          in div (created by Row)
360          in Row (at QuizQuestion.js:42)
361          in div (created by Container)
362          in Container (at QuizQuestion.js:41)
363          in QuizQuestion (at Quiz.js:139)
364          in Quiz (at quiz.test.js:83)
```

**Comment by jsbean** [comment]
Gah, this is maddening:

```Bash
Test Suites: 16 passed, 16 total
Tests:       43 passed, 43 total
Snapshots:   2 obsolete, 1 file obsolete, 0 total
Time:        6.722s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by 1aurend** [comment]
@jsbean should we talk and try to figure this out? I'm seeing very different things than you are...

**Comment by 1aurend** [comment]
> @1aurend, do you get this warning / error on your machine?
> 
> ```shell
> console.error node_modules/react-dom/cjs/react-dom.development.js:530
> 351      Warning: React does not recognize the `randomElement` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `randomelement` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 352          in h2 (at QuizQuestion.js:45)
> 353          in div (created by Row)
> 354          in Row (created by Styled(Row))
> 355          in Styled(Row) (at QuizQuestion.js:44)
> 356          in div (created by Col)
> 357          in Col (created by Styled(Col))
> 358          in Styled(Col) (at QuizQuestion.js:43)
> 359          in div (created by Row)
> 360          in Row (at QuizQuestion.js:42)
> 361          in div (created by Container)
> 362          in Container (at QuizQuestion.js:41)
> 363          in QuizQuestion (at Quiz.js:139)
> 364          in Quiz (at quiz.test.js:83)
> ```

I used to see this error but `jest-styled-components` fixed it. The `randomElement` prop is generated by `styled-components` not by me directly.

**Comment by jsbean** [comment]
Wahoo! This is all fixed in #20. Thanks, @1aurend! 🎉

**Pull request closed without merging**
